version: '3.8'

services:
  mosquitto:
    build: .
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    networks:
      - mi_red_comun

networks:
  mi_red_comun:
    name: mi_red_comun